- 05.md
- 08.md
This document describes how the overpaid Lightning fees are handled and extendes [NUT-05][05] which describes melting tokens (i.e. paying a Lightning invoice). In short, a wallet includes *blank outputs* when paying a Lightning invoice which can be assigned a value by the mint if the user has overpaid Lightning fees. This can be the case due to the unpredictability of Lightning network fees. To solve this issue, we introduce so-called *blank outputs* which are blinded messages with an undetermined value. 
The problem is also described in [this gist](https://gist.github.com/callebtc/a6cc0bd2b6f70e081e478147c40fc578).
> Nut 08/overpaid fees

- 00.md
New token format with URI prefix and version flag that is easier to implement.
Note: this is unfinished, it has to be decided whether we want to use a token JSON that is a dictionary (extendible) or a list (smaller).
> Tokenv3 with URI prefix and version flag

- 09.md
- README.md
Adds NUT-09 that describes how a wallet can retrieve information about the mint using the endpoint `GET /info`.
> Add nut-09: Mint information

- 02.md
This PR is a small addition to the definition of the keyset type, stating that the public keys must be serialized using the compressed public key format used everywhere in bitcoin when building keysets.
This is not unique to bitcoin so I couldn't find a BIP to link to for further information on the format, but information about it is basically found everywhere, including many questions and answers on Stack Overflow and a section of Mastering Bitcoin by Antonopoulos. I chose an article from learnmeabitcoin.com for the link. 
Note that this is also the approach used in one of the [BIPs defining SegWit](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki#restrictions-on-public-key-type), where only compressed keys are accepted, standardizing the length required to share them as …
> Add clarification around public key format mints should use

- test-vectors/00-tests.md
This is just an attempt to show what adding vectors to the NUTs could look like. Happy to hear if there might be a better format or approach. If this looks good, I can take some time and add a bunch more, pulling from the Python, TypeScript, and Go codebases.
I tried to take inspiration from the [BIP-32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) test vectors, but with codeblocks so as to make it easier to copy in some cases.
[Trezor uses a different approach](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) with JSON objects containing the tests, but I find this approach not as universal because in many cases it helps to add failing tests and explain why they should fail, and JSON doesn't support comments.
> Add a few test vectors for NUT-00

- 08.md
For `fee_reserve == 0` (if the payment is internal for example), and for `fee_reserve == 1` the calculation breaks.
> NUT-08: handle log(0) and log(1) possibilities

- 07.md
- README.md
- wallet/cashu_wallet_spec.md
This is necessary in order for a wallet to determine whether a token it used for making a Lightning payment is still in-flight or not.
In short, LN payments can have 3 states but our tokens only 2 (because there's only `spendable` or not). We need another boolean state (`pending`).
Using this, wallets can determine the state of an outgoing Lightning payment as follows:
- if a token is `not spendable` and `not pending`, the payment succeeded
- if a token is `spendable` and `pending`, the payment is in-flight
- if a token is `spendable` and `not pending`, the payment failed
> NUT-07: add new field `pending`

- 04.md
- 06.md
The NUTs do not currently offer insights/recommendations on how to order the list of `BlindedMessage`s that the client builds when it requests minting and splitting tokens. Because ordering those in specific ways is potentially a privacy leak to the mint, advising clients to sort this list of outputs before sending them over is helpful.
The paragraph added to NUT-04 and NUT-06 is the following:
> Note that in order to preserve privacy around the exact amount a client might be trying to build a token for, the client **SHOULD** ensure that the list of `BlindedMessage`s is always ordered by amount in ascending order. For example, a request for tokens expressed like so: `[16, 8, 2, 64, 8]` might imply the client is building a payment for 26 sat; the client should instead order the list like …
> Clarify how clients should order lists of outputs to preserve privacy

- 00.md
Remove `p2pksig` reference in `Proof`, will be specified in separate nut for `P2PK`.
> NUT-00: Remove `p2pksig` reference

- 10.md
- README.md
This is a NUT describing the structure of the well-known `Secret` object that can encode more complex spending conditions. This was previously part of #40 but has been refactored into two separate NUTs, the latter only describing P2PK.
> NUT-10: Spending conditions

- README.md
The readme still has a reference to the now removed cashu_wallet_spec file, leaving a link that returns a `404 — Page Not Found` error. This PR removes that section of the readme.
> Remove reference to `cashu_wallet_spec.md` file in readme

- 12.md
- README.md
> In this document, we present an extension of Cashu's crypto system to allow a user Alice to verify the mint Bob's signature using only Bob's public keys. We explain how another user Carol who receives ecash from Alice can execute the DLEQ proof as well. This is achieved using a Discrete Log Equality (DLEQ) proof. Previously, Bob's signature could only be checked by himself using his own private keys ([NUT-00](00)). 
**More resources:**
- Implementation in Nutshell: https://github.com/cashubtc/cashu/pull/175
- A discussion about the DLEQ proof on Somsens's [gist](https://gist.github.com/RubenSomsen/be7a4760dd4596d06963d67baf140406)
- A discussion on the pros and cons compared to an alternative approach: https://github.com/cashubtc/nutshell/pull/295
**Todo:**
> NUT-12: Chaum-Pedersen DLEQ proofs

- 02.md
I assume `keysets` means that there could be multiple, so shouldn't they be encapsuled in an object?
> Keysets example response

- 11.md
This pull request fixes the conditions for enfording `SIG_ALL`
> Fix signature enforcement in Proof class

- 07.md
Instead of using `secret` in the token state check, we use `Y`. 
This allows third parties to check the state of a token for which they have received the `Y` without being able to spend it. 
Wallets that know `secret` can compute `Y` by `Y = hash_to_curve(secret)`.
Closes: https://github.com/cashubtc/nuts/issues/91
> NUT-07: Token state check with `Y`

- 04.md
- 05.md
- 06.md
This PR changes the "settings" for NUT-4/NUT-5 (minting and melting) that are shown in the `/v1/info` response.
The unit pairs are changed from an array `["method", "unit"]` to an object that now also carries settings for the endpoints.
Example:
```json
{
"method": "bolt11",
"unit": "sat",
"min_amount": 0,
"max_amount": 10000        
}
```
> NUT-4/NUT-5: Method-unit pair is object with settings

- 05.md
The settings for Nut-05 in the info-endpoint should be under the key 5 and not 4
> Nut-05: fix small typo

- 09.md
- 13.md
tests link is not used in NUT09 and tests link in NUT13 should be 13 not 09.
> fix: typo in nut13 tests link

- README.md
Removes Feni from README.md. Feni is deprecated. I think the dev is contributing to GoNuts now (👏👏👏👏)
> Remove Feni from README.md tables

- 00.md
This PR removes two of the three suggested URI schemes from NUT-00. According to RFC 3986 the `//` indicates the start of the Authority part, which is not applicable to a cashu token.
> removed cashu:// and web+cashu:// schemes

- 02.md
- README.md
Proposing to add fees to the mandatory part of the spec as I expect most public mints will require fees at some point. If the fees are not set, we should assume it as being 0.
Moved around some existing text. The new part is:
Keysets indicate the fee `input_fee_ppk` that is charged when a `Proof` of that keyset is spent as an input to a transaction. The fee is given in parts per thousand (ppk) per input measured in the `unit` of the keyset and the sum is rounded up to the next larger integer. 
As an example, we construct a transaction spending 3 inputs (`Proofs`) from a keyset with unit `sat` and `input_fee_ppk` of `100`. A fee of `100 ppk` means `0.1 sat` per input. The sum of the fees would be 300 ppk for this transaction and the mint would charge `1 sat` in fees (`ceil(0.3) == 1`). The …
> Add fees to NUT-02

- README.md
I'm in favor as removing these from the NUTs readme in favor for awesome cashu or similar as suggested in  https://github.com/cashubtc/nuts/issues/81 but if they are here cdk should be updated
> update cdk mint

- error_codes.md
Alternative to #131 
I found having having the error codes split across multiple files to be confusing since the same error can be used in multiple nuts. This change keep all the error codes in one file while noting what nut(s) each error code is relevant to.
Open to comments on which one others prefer.
> refactor: one error code file

- 05.md
This pull request removes the reference to the old `paid` flag and `proof` in the code. The second request now includes a payment `state` and, if `"PAID"`, a `payment_preimage` as a proof of payment.
> NUT-05: Remove reference to old `paid` flag and `proof`

- 09.md
Update to reference Nut 13 instead of Self reference (nut 9)
> Nut-09 - Update 09.md as references self instead of Nut-13

- 18.md
json says `"r"` for single use payments while the description says `"s"`
I think it should be `"s"`
> NUT-18: fix typo

- 07.md
- 10.md
- 11.md
- 14.md
The state check MUST return the states in the same order as the Proofs in the request.
> NUT-07: explicitly mention order

- 06.md
fixes https://github.com/cashubtc/nuts/issues/62
> NUT-06: add urls field

- 15.md
Change supported flag for MPP from 
```
"15": []
```
to
```
"15": {
"methods": []
}
```
Tracking:
> Fix: nut-15 methods flag

- 10.md
link to NUT-14 is broken because there is a missing reference at the end of the document
> NUT-10: fix broken link

- README.md
Correct the numbering for the Clear and Blind authentication specifications in the documentation.
> Fix nut numbers 21 and 22 in README

- 12.md
Before: https://github.com/cashubtc/nuts/blob/main/01  
After: https://github.com/cashubtc/nuts/blob/main/01.md
> fix: link to NUT with [] instead of ()

- error_codes.md
add error code for failed lightning payments in melts. If wallets see this error they can be sure the proofs are not stuck in a pending state.
> error code for failed lightning payments

- 15.md
Clarify that the `amount` parameter for the requested payment is specified in millisats (msat) in the documentation.
Tracking:
> NUT-15: Specify MPP amount in millisats (msat)

- 12.md
- 13.md
Enhance clarity in the documentation by refining the hash function description and adding important notes regarding DLEQ proofs and test vectors.
> Improve documentation for NUT-12 and add note tags for NUT-13

- 22.md
This addition makes sure that `AuthProofs` can not be pinned by enforcing NUT-12 DLEQ proofs on signature reponses
> Add mandatory DLEQs to nut-22

- 02.md
- 10.md
Found these two typos:
- nut02: `keyest` -> `keyset`
- nut10: `autorize` -> `authorize`
> Fixes a few typos

- 11.md
Consolidates the changes I recommended as part of my review of PR #149
> Clarifications to multisig
