cashubtc/nuts

README.md
see https://github.com/cashubtc/cashu-feni/pull/42
=> add add Feni to nut-08 list

00.md
=> Fix typo in NUT-00

README.md
=> closes #16

README.md
=> add `cashu-crab` and `cashu-rs-mint` to `README`

00.md
=> add G description for completeness

03.md
This PR fixes the section titles of NUT-03 which had the old section titles from NUT-06. I didn't fix the numbers themselves (like switching from 6.1 to 3.1) but decided to remove the numbers entirely, since all other NUTs do not use numbered sections.
=> Fix NUT-03 section titles

tests/00-tests.md
This pull request updates the test vectors for the hash to curve function.
=> Update test vectors

16.md, README.md
Closes https://github.com/cashubtc/nuts/pull/31
=> Add animated QR codes

tests/00-tests.md
Based on https://github.com/cashubtc/cdk/blob/main/crates/cdk/src/dhke.rs#L219, I was finally able to figure out why my seemingly very simple crypto was not working.
=> Fix incorrect test vector

06.md
This PR updates the contact information structure. 
The main change is in the representation of contact information, which is now a structured object instead of an array. This allows for a more explicit and readable representation of contact types and values.
=> NUT-6: update contact info

03.md
> one worth 32 sat and another two worth 16 sat.
sums to three proofs
=> NUT-03: fix number of proofs in "Swap to send" example

00.md
mint URL sanitize, add description to TokenV4
=> NUT-00: Fix mint URL sanitization

README.md
supersedes https://github.com/cashubtc/nuts/pull/118
=> README: add minibits, fix nutshell link

06.md
fixes https://github.com/cashubtc/nuts/issues/138
implementations in:
* nutshell PR: https://github.com/cashubtc/nutshell/pull/611
* cdk PR: https://github.com/cashubtc/cdk/pull/313
=> NUT-06: add time field

error_codes.md
`Amount outside of limit range` error also applies to NUT-05
=> error codes: nut-05 amount outside of limit code

README.md
update per supported nuts listed on nutmix  https://github.com/lescuer97/nutmix
=> Update README.md-nutmix nuts

README.md
for Gonuts mint supported NUTS here:
https://github.com/elnosh/gonuts
=> Update README.md-update mint support

22.md
"not subject" to "not the subject"
"After each for each " to "For each"
=> Update 22.md- 2 small typos in text

12.md
Apply Prettier to standardize code formatting across the project.
=> NUT-12: Format with Prettier

error_codes.md
=> feat: add error codes for request verification

README.md
Adds nuts that nutmix support to list
=> Update nutmix features

04.md
For easier reading: https://github.com/ok300/nuts/blob/ok300-nut04-expiry/04.md
=> NUT-04: Add more details about `expiry`

23.md
Per question in Matrix and @lollerfirst answer
=> Update 23.md-update PAID ISSUED description

20.md
=> NUT-20: specify public key format
